services:
  - type: web
    name: meiga-sabela-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: NODE_ENV
        value: production